USE customer_behavior;
SELECT * FROM customer limit 15;

#Q1. What is the total revenue generated by male vs. female customers?
SELECT gender, SUM(purchase_amount) AS revenue 
FROM customer
GROUP BY gender;

#Q2. Which customers used a discount but still spent more than the average purchase amount? 
SELECT customer_id, purchase_amount
FROM customer
WHERE discount_applied = 'Yes' and purchase_amount >= (select AVG(purchase_amount) from customer);

#Q3. Which are the top 5 products with the highest average review rating?
SELECT item_purchased, ROUND(AVG(review_rating),2) AS "Average Product Rating"
FROM customer
GROUP BY item_purchased
ORDER BY AVG(review_rating) DESC
LIMIT 5;

#Q4. Compare the average Purchase Amounts between Standard and Express Shipping. 
SELECT shipping_type, ROUND(AVG(purchase_amount),2)
FROM customer
WHERE shipping_type in ('Standard','Express')
GROUP BY shipping_type;

#Q5. Do subscribed customers spend more? Compare average spend and total revenue 
#between subscribers and non-subscribers.
SELECT subscription_status,
       COUNT(customer_id) AS total_customers,
       ROUND(AVG(purchase_amount),2) AS avg_spend,
       ROUND(SUM(purchase_amount),2) AS total_revenue
FROM customer
GROUP BY subscription_status
ORDER BY total_revenue,avg_spend DESC;

#Q6. Which 5 products have the highest percentage of purchases with discounts applied?
SELECT item_purchased,
       ROUND(100.0 * SUM(CASE WHEN discount_applied = 'Yes' THEN 1 ELSE 0 END)/COUNT(*),2) AS discount_rate
FROM customer
GROUP BY item_purchased
ORDER BY discount_rate DESC
LIMIT 5;

#-Q7. Segment customers into New, Returning, and Loyal based on their total 
-- number of previous purchases, and show the count of each segment. 
with customer_type as (
SELECT customer_id, previous_purchases,
CASE 
    WHEN previous_purchases = 1 THEN 'New'
    WHEN previous_purchases BETWEEN 2 AND 10 THEN 'Returning'
    ELSE 'Loyal'
    END AS customer_segment
FROM customer)

select customer_segment,count(*) AS "Number of Customers" 
from customer_type 
group by customer_segment;

#Q8. What are the top 3 most purchased products within each category? 
WITH item_counts AS (
    SELECT category,
           item_purchased,
           COUNT(customer_id) AS total_orders,
           ROW_NUMBER() OVER (PARTITION BY category ORDER BY COUNT(customer_id) DESC) AS item_rank
    FROM customer
    GROUP BY category, item_purchased
)
SELECT item_rank,category, item_purchased, total_orders
FROM item_counts
WHERE item_rank <=3;

#Q9. Are customers who are repeat buyers (more than 5 previous purchases) also likely to subscribe?
SELECT subscription_status, COUNT(customer_id) AS repeat_buyers
FROM customer
WHERE previous_purchases > 5
GROUP BY subscription_status;

#Q10. What is the revenue contribution of each age group? 
SELECT 
    age_group,
    SUM(purchase_amount) AS total_revenue
FROM customer
GROUP BY age_group
ORDER BY total_revenue desc;

#Q11. Which product categories generate the highest profit opportunity?
SELECT
    category,
    SUM(purchase_amount) AS revenue,
    ROUND(100 * SUM(purchase_amount) /
    (SELECT SUM(purchase_amount) FROM customer),2) AS revenue_share
FROM customer
GROUP BY category
ORDER BY revenue DESC;

#Q12Which locations generate the highest revenue?
SELECT
    location,
    SUM(purchase_amount) AS revenue,
    COUNT(*) AS orders,
    ROUND(AVG(purchase_amount),2) AS avg_order_value
FROM customer
GROUP BY location
ORDER BY revenue DESC;

#Q13. Monthly/Seasonal Sales Ranking
SELECT
    season,
    category,
    SUM(purchase_amount) revenue,
    DENSE_RANK() OVER(
        PARTITION BY season
        ORDER BY SUM(purchase_amount) DESC
    ) ranking
FROM customer
GROUP BY season, category;

#Q14. Revenue by Gender and Category
SELECT
    gender,
    category,
    SUM(purchase_amount) revenue
FROM customer
GROUP BY gender, category
ORDER BY gender, revenue DESC;

#Q15. Which customers never use discounts?
SELECT
    customer_id,
    SUM(purchase_amount) total_spend
FROM customer
WHERE discount_applied='No'
GROUP BY customer_id
ORDER BY total_spend DESC;

#Q16. Which season generates the highest sales?
SELECT
    season,
    SUM(purchase_amount) revenue,
    COUNT(*) total_orders,
    ROUND(AVG(purchase_amount),2) avg_order
FROM customer
GROUP BY season
ORDER BY revenue DESC;

#Q17. 4. Which age group buys which category the most?
SELECT
    age_group,
    category,
    COUNT(*) purchases
FROM customer
GROUP BY age_group, category
ORDER BY age_group, purchases DESC;

#Q18. Which color sells the most?
SELECT
    color,
    COUNT(*) total_sales,
    SUM(purchase_amount) revenue
FROM customer
GROUP BY color
ORDER BY total_sales DESC;

#Q19. Which size is most demanded?
SELECT
    size,
    COUNT(*) total_orders
FROM customer
GROUP BY size
ORDER BY total_orders DESC;

#Q20. Which products have high ratings but low sales?
SELECT
    item_purchased,
    COUNT(*) total_orders,
    ROUND(AVG(review_rating),2) avg_rating
FROM customer
GROUP BY item_purchased
HAVING AVG(review_rating)>=4.5
ORDER BY total_orders;